import axios from 'axios';

// Create an axios instance
const apiClient = axios.create({
  baseURL: '/api', // Relative path to be intercepted or proxied
    headers: {
        'Content-Type': 'application/json',
          },
          });

          // Mock data store
          const MOCK_PAGES: Record<string, { title: string; content: string; created_at: string }> = {
            'about-rsmc': {
                title: 'About RSMC',
                    content: `
                          <h2>Who We Are</h2>
                                <p>The Regional Specialized Meteorological Centre (RSMC) is a designated institution responsible for providing severe weather forecasting and guidance to national meteorological services in the region.</p>
                                      <p>Established under the framework of the World Meteorological Organization (WMO), our centre plays a critical role in disaster risk reduction and climate resilience.</p>
                                            <h3>Our History</h3>
                                                  <p>Founded in 1995, RSMC has grown to become a hub of excellence in tropical cyclone forecasting and regional climate modeling.</p>
                                                      `,
                                                          created_at: new Date().toISOString(),
                                                            },
                                                              'mandate': {
                                                                  title: 'Our Mandate',
                                                                      content: `
                                                                            <h2>Core Responsibilities</h2>
                                                                                  <ul>
                                                                                          <li>Provide real-time guidance on severe weather events including tropical cyclones.</li>
                                                                                                  <li>Conduct research and development in regional meteorology.</li>
                                                                                                          <li>Build capacity for National Meteorological and Hydrological Services (NMHSs).</li>
                                                                                                                  <li>Disseminate specialized products for aviation and marine sectors.</li>
                                                                                                                        </ul>
                                                                                                                            `,
                                                                                                                                created_at: new Date().toISOString(),
                                                                                                                                  },
                                                                                                                                    'services': {
                                                                                                                                        title: 'Our Services',
                                                                                                                                            content: `
                                                                                                                                                  <h2> Meteorological Services</h2>
                                                                                                                                                        <p>We offer a range of specialized services tailored to the needs of the region:</p>
                                                                                                                                                              <ul>
                                                                                                                                                                      <li><strong>Severe Weather Forecasting:</strong> Early warning systems for cyclones and heavy rainfall.</li>
                                                                                                                                                                              <li><strong>Climate Services:</strong> Seasonal forecasts and climate change analysis.</li>
                                                                                                                                                                                      <li><strong>Training:</strong> Workshops and seminars for meteorologists.</li>
                                                                                                                                                                                            </ul>
                                                                                                                                                                                                `,
                                                                                                                                                                                                    created_at: new Date().toISOString(),
                                                                                                                                                                                                      },
                                                                                                                                                                                                        'products': {
                                                                                                                                                                                                            title: 'Products',
                                                                                                                                                                                                                content: `
                                                                                                                                                                                                                      <h2>Weather Products</h2>
                                                                                                                                                                                                                            <p>Access our latest technical products:</p>
                                                                                                                                                                                                                                  <ul>
                                                                                                                                                                                                                                          <li>Synoptic Charts</li>
                                                                                                                                                                                                                                                  <li>Satellite Imagery Analysis</li>
                                                                                                                                                                                                                                                          <li>NWP Model Outputs</li>
                                                                                                                                                                                                                                                                  <li>Tropical Cyclone Tracks</li>
                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                            `,
                                                                                                                                                                                                                                                                                created_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                  // Add a request interceptor to mock responses
                                                                                                                                                                                                                                                                                  apiClient.interceptors.request.use(async (config) => {
                                                                                                                                                                                                                                                                                    // Simulate network delay
                                                                                                                                                                                                                                                                                      await new Promise(resolve => setTimeout(resolve, 300));

                                                                                                                                                                                                                                                                                        // Mock GET /pages/:slug
                                                                                                                                                                                                                                                                                          if (config.url?.startsWith('/pages/') && config.method === 'get') {
                                                                                                                                                                                                                                                                                              const slug = config.url.split('/').pop();
                                                                                                                                                                                                                                                                                                  const page = MOCK_PAGES[slug || ''];
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                          if (page) {
                                                                                                                                                                                                                                                                                                                throw {
                                                                                                                                                                                                                                                                                                                        response: {
                                                                                                                                                                                                                                                                                                                                  status: 200,
                                                                                                                                                                                                                                                                                                                                            data: { ...page, slug },
                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                            isMock: true
                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                            throw {
                                                                                                                                                                                                                                                                                                                                                                                    response: {
                                                                                                                                                                                                                                                                                                                                                                                              status: 404,
                                                                                                                                                                                                                                                                                                                                                                                                        data: { detail: 'Not found' },
                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                        isMock: true
                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                      return config;
                                                                                                                                                                                                                                                                                                                                                                                                                                      }, (error) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        return Promise.reject(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                        // Add a response interceptor to handle the thrown mock responses
                                                                                                                                                                                                                                                                                                                                                                                                                                        apiClient.interceptors.response.use(
                                                                                                                                                                                                                                                                                                                                                                                                                                          (response) => response,
                                                                                                                                                                                                                                                                                                                                                                                                                                            (error) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (error.isMock) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Promise.resolve(error.response);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              return Promise.reject(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default apiClient;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                